services:
  db:
    image: paulgiraldo/devops-mysql:latest
    container_name: paul_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: usuariosdb
    volumes:
      - paul_db_data:/var/lib/mysql
    ports:
      - 3398:3306
    networks:
      - paul_my_network
  app:
    image: paulgiraldo/devops-app:latest
    container_name: paul_app
    environment:
      MY_DATABASE_DRIVER: "mysql"
      DB_HOST: db
      DB_USER_NAME: root
      DB_PASSWORD: rootpwd
      DB_NAME: usuariosdb
      DB_PORT: 3306
    depends_on:
      - db
    ports:
      - 8098:3000
    restart: always
    networks:
      - paul_my_network      
  dbBackup:
    image: fradelg/mysql-cron-backup
    container_name: paul_dbBackup
    depends_on:
      - db
    restart: always
    volumes:
      - ./backup:/backup
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=rootpwd
      - MYSQL_DB=usuariosdb
      - CRON_TIME= 0 * * * *
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - TIMEOUT=10s
      - INIT_BACKUP=1      
    networks:
      - paul_my_network

volumes:
  paul_db_data:

networks:
  paul_my_network:
    driver: bridge

