version: "3"

services:
  db:
    image: mysql:5.7
    container_name: db_mysql_paul
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: usuariosdb
    volumes:
      - db_data:/var/lib/mysql
      - ./data/mysql_data.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3398:3306
    networks:
      - my_network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MY_DATABASE_DRIVER: "mysql"
      DB_HOST: db_mysql_paul
      DB_USER_NAME: root
      DB_PASSWORD: rootpwd
      DB_NAME: usuariosdb
      DB_PORT: 3398
    depends_on:
      - db
    ports:
      - 8098:3000
    restart: always
    networks:
      - my_network
volumes:
  db_data:

networks:
  my_network:
    driver: bridge

