version: "3"

services:
  db:
    image: mysql:5.7
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: usuarios
    volumes:
      - db_data:/var/lib/mysql
      - ./data/mysql_data.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - my_network
  app:
    image: paulgiraldo/modulo3-backend03:latest
    environment:
      MY_DATABASE_DRIVER: "mysql"
      DB_HOST: db
      DB_USER_NAME: root
      DB_PASSWORD: rootpwd
      DB_NAME: usuarios
      DB_PORT: 3306
    depends_on:
      - db
    ports:
      - 8081:3000
    restart: always
    networks:
      - my_network
volumes:
  db_data:

networks:
  my_network:
    driver: bridge

