apiVersion: v1
kind: Namespace
metadata:
  name: paulgiraldo-modulo3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: paulgiraldo-modulo3
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paulgiraldo-configmap
  namespace: paulgiraldo-modulo3
data:
  MY_DATABASE_DRIVER: "mysql"
  DB_HOST: db
  DB_USER_NAME: root
  DB_NAME: usuarios_db
  DB_PORT: "3306"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-script-inicial
  namespace: paulgiraldo-modulo3
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS usuarios_db;
    USE usuarios_db;
    CREATE TABLE IF NOT EXISTS usuarios (
        id INT AUTO_INCREMENT PRIMARY KEY,
        nombre VARCHAR(50),
        apellido VARCHAR(50),
        edad INT,
        sexo CHAR(1)
    );

    INSERT INTO usuarios (nombre, apellido, edad, sexo) VALUES ('Maria', 'Rojas', 30, 'F');

---
apiVersion: v1
kind: Secret
metadata:
  name: paulgiraldo-secret
  namespace: paulgiraldo-modulo3
type: Opaque
data:
  DB_PASSWORD: cm9vdHB3ZA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: paulgiraldo-modulo3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: paulgiraldo-secret
                key: DB_PASSWORD
          - name: MYSQL_DATABASE
            value: usuarios_db
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
          - name: init-scripts
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: init-scripts
          configMap:
            name: mysql-script-inicial
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: paulgiraldo-modulo3
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: paulgiraldo-modulo3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: paulgiraldo/modulo3-backend:latest
        envFrom:
        - configMapRef:
            name: paulgiraldo-configmap       
        env:
          - name: DB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: paulgiraldo-secret
                key: DB_PASSWORD
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: paulgiraldo-modulo3
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 3000
